apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"traceID":"(\w+)"'
          url: 'http://jaeger:16686/trace/$${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    secureJsonData:
      password: secret
    jsonData:
      database: products
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['job', 'instance', 'service.name']
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{service_name="${__data.fields.serviceName}"} |= "${__data.fields.traceID}"'
