global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'products-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['products-api:3000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        target_label: '__name__'
        replacement: '${1}'
        action: replace
      - regex: 'exported_.*'
        action: labeldrop

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
